name: Tests
on:
  push:
    branches:
      - master
      - dev
jobs:
  unit-test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker

    steps:
      - name: "Use docker"
        run: docker run --rm -v $PWD:/home/ -w /home  /bin/zsh
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Test run"
        shell: bash
        run: make tests_run
      - name: "Coverage"
        shell: bash
        run: make coverage
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: "Say hello world"
        shell: bash
        run: "echo Welcome to the github Action workshop !"
